# test.yml
name: Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Generate Graph and Markdown
      run: python script.py

    - name: Commit and Push Changes
      run: |
        git config --global user.email "suim.park@github.com"
        git config --global user.name "suim-park"
        git add .
        git commit -m "Generate graph and markdown"
        git push origin main

    - name: lint
      run: make lint

    - name: format
      run: make format

    - name: deploy
      run: make deploy

